/// <reference types="@woofx3/module-sdk/function-ctx" />

// Every !dadjoke draws from this list. A joke said recently is skipped so a
// busy chat doesn't hear the same one twice in a row.
var JOKES = [
    "My GPS and I broke up. It kept telling me where to go.",
    "I started a band called 1023 MB. We still haven't got a gig.",
    "My vacuum cleaner quit its job. It said the work really sucked.",
    "I tried to write a song about tortillas. It turned out more like a wrap.",
    "The calendar on my wall is nervous. Its days are numbered.",
    "I asked my stapler for advice. It told me to stick with what holds things together.",
    "My houseplant got a promotion. It's now the branch manager.",
    "I bought a ceiling fan for my friend. He's a big supporter of the ceiling.",
    "My toaster refuses to help. It always pops up at the wrong time.",
    "The math teacher brought a ladder to class. She wanted to reach higher numbers.",
    "I told my cat a joke about yarn. She didn't get it, but she was very entertained.",
    "My shoes are great at keeping secrets. They never let a word slip, only a foot.",
    "The broom was late to work. It overswept.",
    "I gave my clock a vacation. It needed some time off.",
    "My pencil started a podcast. It's mostly pointless.",
    "The bakery hired a new guy. He really knows how to make dough.",
    "I tried to argue with a mountain. It wouldn't budge on any of its peaks.",
    "My fridge started telling jokes. They were pretty cool.",
    "The baseball player got a job at the bank. He was good at stealing bases, not money.",
    "I named my dog Five Miles. Now I can tell people I walk Five Miles every day.",
    "The orange stopped rolling down the hill. It ran out of juice.",
    "My electrician friend is shocking at parties. In a good way.",
    "The ghost failed his driving test. He kept going through walls.",
    "My phone's battery and I have a lot in common. We both lose energy around three in the afternoon.",
    "The skeleton skipped the party. He had no body to go with.",
    "I asked a lighthouse how it was doing. It said things were looking bright.",
    "The cow got a job as an astronaut. She was the first to jump over the moon officially.",
    "My socks got a hole in them. Now they're holey socks.",
    "I tried to catch some fog. I mist.",
    "The chicken joined a band. It had the drumsticks.",
    "My wallet is like an onion. Opening it makes me cry.",
    "I asked the librarian for books about paranoia. She whispered, they're right behind you.",
    "The duck went to the doctor. She got a bill.",
    "I got a job at a calendar factory. They fired me for taking a day off.",
    "My train of thought just left the station. No idea where it went.",
    "The pirate couldn't learn the alphabet. He kept getting lost at C.",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "The bee got married. She found her honey.",
    "The coffee filed a police report. It got mugged.",
    "My friend lost his job at the orange juice factory. He couldn't concentrate.",
    "The banana went to the doctor. It wasn't peeling well.",
    "The cookie went to the hospital. It felt crummy.",
    "I used to hate facial hair. Then it grew on me.",
    "The magician lost his temper. He pulled his hare out.",
    "Two antennas got married. The ceremony was okay, but the reception was amazing.",
    "I told my plants a bedtime story. Now they're all asleep in their beds.",
    "The music teacher got locked out. Her keys were inside the piano.",
    "The snowman checked his phone. He wanted to see the forecast for his future.",
    "My keyboard and I don't get along. It always pushes my buttons.",
    "I bought a book on anti-gravity. I couldn't put it down.",
    "My dentist told a great story. It was really filling.",
    "The tree went to the dentist. It needed a root canal.",
    "I tried to sue the airport for losing my luggage. I lost my case.",
    "The fish went to school. It was the top of its class, er, school.",
    "The cheese was proud of itself. It was grate.",
    "The sun skipped college. It already had a million degrees.",
    "The clock got hungry. It went back four seconds.",
    "My computer caught a cold. It had too many windows open.",
    "The robot went on vacation. It needed to recharge.",
    "The farmer counted his cows. He got 196, but when he rounded them up he had 200.",
    "The pig sat in the sun too long. Now he's bacon.",
    "The cat got first place at the talent show. She was purr-fect.",
    "The sandwich got a part in the movie. It was on a roll.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm reading a book about glue. I just can't put it down.",
    "The calendar asked for a date. The clock said it was too busy.",
    "The pizza wouldn't stop telling jokes. They were too cheesy.",
    "The rabbit opened a bakery. It specialized in hot cross bunnies.",
    "My friend opened a restaurant on the moon. Great food, but no atmosphere.",
    "The shovel was a great invention. It was truly groundbreaking.",
    "The math book looked sad. It had too many problems.",
    "The wind turbine is my favorite fan. It's a big supporter of clean energy.",
    "I'm on a seafood diet. I see food and I eat it.",
    "The dinosaur couldn't clap. It was extinct.",
    "The bread was the best at its job. It always rose to the occasion.",
    "The light bulb failed its test. It wasn't very bright that day.",
    "I asked my dog what two minus two is. He said nothing.",
    "The squirrel was great at skateboarding. He had nuts skills.",
    "I invented a new word. Plagiarism.",
    "The cat was a great musician. She knew every mewsic note.",
    "My boss told me to have a good day. So I went home.",
    "The penguin built a house. Igloos it together.",
    "The astronaut broke up with his girlfriend. He needed space.",
    "The detective was great at finding bread. He always followed the crumbs.",
    "I made a pun about a wizard. It was Hogwarts of fun.",
    "The plumber retired. He was drained.",
    "The cloud got a job as a teacher. It was great at raining in the students.",
    "The volcano told a great joke. Everyone erupted with laughter.",
    "The paper airplane got a promotion. It really took off.",
    "The carpet store had a sale. Prices were floored.",
    "I found a book about mazes. I got lost in it.",
    "The Lego set got upset. It had to pick up the pieces.",
    "The pirate's favorite letter isn't R. It's the C he loves.",
    "The lemon got a job. It was great at making things zesty.",
    "The tortoise opened a store. Business was slow.",
    "My friend bought a used car. It came with a horn that only played polka.",
    "The bee needed glasses. It kept running into flowers it didn't mean to visit.",
    "I lost my job at the bank. A lady asked me to check her balance, so I pushed her over.",
    "The mushroom got invited to every party. He was a fungi.",
    "The bike got stuck in the mud. It was spoke-less.",
    "The fork, knife and spoon had a meeting. It was utensil.",
    "The whale cried at the movie. It was a real blubber.",
    "The trampoline got a raise. Things were looking up.",
    "The vampire went to art school. He wanted to learn to draw blood.",
    "The donut quit its job. It was fed up with the hole thing.",
    "I asked the corn for a story. It was a-maize-ing.",
    "The pencil sharpener had a great idea. It got right to the point.",
    "My grandpa has the heart of a lion. And a lifetime ban from the zoo.",
    "The cat walked into a store. It asked for a cat-alogue.",
    "The owl went to college. It wanted to be a hoot-er scholar.",
    "The candle went to a party. It was the life of the party until it burned out.",
    "The baby corn asked where its dad was. Mom said, Pop corn.",
    "The traffic light turned red. It was embarrassed to change in front of everyone.",
    "The tennis ball got married. The racket was huge.",
    "The road crossed the chicken. Nobody saw that coming.",
    "I tried to write with a broken pen. It was useless, but I wrote it off.",
    "The muffin was nervous. It didn't want to be the butter of jokes.",
    "I asked my mom for a hot dog. She said, I'm not a dog.",
    "The ladder told everyone about its job. It was always climbing.",
    "The seal went to art school. It wanted to learn how to draw a seal of approval.",
    "The sheep went to space. It was the first to visit the baaa-ckside of the moon.",
    "The spider got a job. It was a web designer.",
    "My friend said he's going to paint his room silver. I said that would be sterling.",
    "The clown went to the doctor. He was feeling funny.",
    "The ant was a great boss. It was in charge of the colony and never bugged anyone.",
    "The jar of pickles got a job. It was a big dill.",
    "The football coach went to the vending machine. He wanted his quarter back.",
    "The ruler was the leader of the school supplies. It made all the rules.",
    "The deer got a part-time job. It needed more doe.",
    "The steak went to court. It was a rare case.",
    "The stone got good grades. It was a real rock star.",
    "I don't trust stairs. They're always up to something.",
    "I'd tell you a joke about construction, but I'm still working on it.",
    "I'd tell you a joke about time travel, but you didn't like it.",
    "I'd tell you a joke about an empty pool, but there's nothing in it.",
    "I'd tell you a joke about a broken clock, but it's not the right time.",
    "I'd tell you a joke about paper, but it's tearable.",
    "I'd tell you a joke about a dull pencil, but it has no point.",
    "I'd tell you a joke about a ceiling, but it's over your head.",
    "I'd tell you a joke about a stop sign, but I'll end it here.",
    "I'd tell you a joke about the wind, but it would blow you away.",
    "I'd tell you a joke about a bad egg, but it's rotten.",
    "I'd tell you a joke about a slow snail, but it would take too long.",
    "I'd tell you a joke about a library, but it would be overdue.",
    "I'd tell you a joke about a sandwich, but it's too corny on rye.",
    "I'd tell you a joke about a bridge, but you'd never get over it.",
    "I'd tell you a joke about a garden, but it needs time to grow on you.",
    "I'd tell you a joke about a lighthouse, but it's not very bright.",
    "What do you call a fake noodle? An impasta.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What do you call a sleeping bull? A bulldozer.",
    "What do you call a fish with no eyes? A fsh.",
    "What do you call a deer with no eyes? No idea.",
    "What do you call a pig that does karate? A pork chop.",
    "What do you call a dog that does magic? A labracadabrador.",
    "What do you call a dinosaur with a big vocabulary? A thesaurus.",
    "What do you call an alligator in a vest? An investigator.",
    "What do you call a cow with no legs? Ground beef.",
    "What do you call a man with a rubber toe? Roberto.",
    "What do you call a snowman in July? A puddle.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "What do you call a belt made of watches? A waist of time.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "What do you call a parade of rabbits hopping backwards? A receding hare line.",
    "What do you call a boomerang that won't come back? A stick.",
    "What do you call a nervous javelin thrower? Shaky spear.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What do you call a cow in an earthquake? A milkshake.",
    "What do you call a sad strawberry? A blueberry.",
    "What do you call a pony with a sore throat? A little horse.",
    "What do you call a group of musical whales? An orca-stra.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call a cold dog? A chili dog.",
    "What do you call a pile of cats? A meowntain.",
    "What do you call a shoe made of a banana? A slipper.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why don't eggs tell secrets? They might crack up.",
    "Why did the cookie cry? Its mom was a wafer so long.",
    "Why did the student eat his homework? The teacher said it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the picture go to jail? It was framed.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "Why can't a bicycle stand on its own? It's two tired.",
    "Why did the tomato turn red? It saw the salad dressing.",
    "Why did the golfer bring an extra pair of socks? In case he got a hole in one.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "Why don't oysters share? They're shellfish.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why did the music teacher need a ladder? To reach the high notes.",
    "Why are elevator jokes so good? They work on many levels.",
    "Why did the banana go to the party? It was a-peeling.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why do cows wear bells? Their horns don't work.",
    "Why did the coffee taste like dirt? It was ground a few minutes ago.",
    "Why did the bear dissolve in water? It was a polar bear.",
    "Why do bees have sticky hair? They use honeycombs.",
    "Why did the frog take the bus? His car got toad.",
    "Why did the invisible man turn down the job? He couldn't see himself doing it.",
    "Why do seagulls fly over the sea? If they flew over the bay, they'd be bagels.",
    "Why did the lion eat the tightrope walker? He wanted a well-balanced meal.",
    "Why did the gym close down? It just didn't work out.",
    "Why did the teddy bear skip dessert? It was already stuffed.",
    "Why did the cow cross the road? To get to the udder side.",
    "Why did the duck get in trouble? It was caught quacking jokes in class.",
    "Why did the drum take a nap? It was beat.",
    "Why don't mountains get cold? They wear snow caps.",
    "Why do fish live in salt water? Pepper makes them sneeze.",
    "Why did the chicken go to the séance? To get to the other side.",
    "Why was the broom late? It swept in.",
    "Why did the belt go to jail? It held up a pair of pants.",
    "Why are ghosts bad liars? You can see right through them.",
    "Why did the kid bring a ladder to school? He wanted to go to high school.",
    "Why did the photo go to the dentist? It needed to get its teeth developed.",
    "Why did the boy throw butter out the window? To see a butterfly.",
    "Why did the soccer player bring string? To tie the game.",
    "Why don't calendars ever get lonely? They have lots of dates.",
    "Why do melons have weddings? Because they cantaloupe.",
    "Why did the pony get sent to his room? He wouldn't stop horsing around.",
    "Why don't sharks eat clowns? They taste funny.",
    "Why did the cat sit on the computer? To keep an eye on the mouse.",
    "Why was the baby strawberry crying? Its parents were in a jam.",
    "Why don't ants get sick? They have tiny ant-ibodies.",
    "Why did the robot get angry? Someone kept pushing its buttons.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "How does the moon cut its hair? Eclipse it.",
    "How do you organize a space party? You planet.",
    "How do trees get online? They log in.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "How does a cucumber become a pickle? It goes through a jarring experience.",
    "How do you make an octopus laugh? With ten-tickles.",
    "How do you fix a cracked pumpkin? With a pumpkin patch.",
    "How does a scientist freshen her breath? With experi-mints.",
    "How do you throw a party in outer space? You planet in advance.",
    "How do you make a lemon drop? Just let it fall.",
    "How do you get a farm girl to like you? A tractor.",
    "How do you weigh a whale? At a whale-weigh station.",
    "How do cows stay up to date? They read the moos-paper.",
    "How do you know if a bee is on the phone? You get a buzzy signal.",
    "How does a train eat? It goes chew chew.",
    "How do you talk to a giant? Use big words.",
    "How do you find a lost cow? Follow the moo-tracks.",
    "How do you make a hot dog stand? Take away its chair.",
    "How does a snowman get around? It rides an icicle.",
    "How do you cut the ocean in half? With a sea-saw.",
    "How do you keep a bagel from getting away? Put lox on it.",
    "How do you make a strawberry shake? Take it to a scary movie.",
    "How does a duck buy lip balm? She puts it on her bill.",
    "How do you get a squirrel to like you? Act a little nutty.",
    "How do you make an egg roll? You push it down a hill.",
    "What did the ocean say to the shore? Nothing, it just waved.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What did the buffalo say when his son left? Bison.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "What did one hat say to the other? You stay here, I'll go on a head.",
    "What did the big flower say to the little flower? Hi, bud.",
    "What did one plate say to the other? Dinner's on me.",
    "What did the zero say to the eight? Nice belt.",
    "What did the coffee say to the sugar? You make my life sweeter.",
    "What did the pirate say on his 80th birthday? Aye matey.",
    "What did the tree say to the wind? Leaf me alone.",
    "What did the cheese say when it looked in the mirror? Halloumi.",
    "What did the mountain climber name his son? Cliff.",
    "What did the nut say when it sneezed? Cashew.",
    "What did the triangle say to the circle? You're pointless.",
    "What did the hamburger name its baby? Patty.",
    "What did the stamp say to the envelope? Stick with me and we'll go places.",
    "What did the left sock say to the right sock? We make a great pair.",
    "What did the dog say to the tree? Bark.",
    "What did the rug say to the floor? Don't move, I've got you covered.",
    "What did the pencil say to the paper? I dot my i's on you.",
    "What did the blanket say to the bed? Don't worry, I've got you covered.",
    "What did the volcano say to its sweetheart? I lava you.",
    "What did the bread say to the butter? You're on a roll.",
    "What did one elevator say to the other? I think I'm coming down with something.",
    "What did the sushi say to the bee? Wasabi.",
    "What did the cat say when it lost its toy? You've got to be kitten me.",
    "What did the duck say after shopping? Put it on my bill.",
    "What did the calculator say to the student? You can count on me.",
    "What did the shark say when it ate the clownfish? This tastes a little funny.",
    "What did the snail say riding on the turtle's back? Wheee.",
    "What did one toilet say to the other? You look a bit flushed.",
    "What did the drummer name his twin daughters? Anna One, Anna Two.",
    "What did the policeman say to his belly button? You're under a vest.",
    "What did the egg say to the frying pan? You crack me up.",
    "What did the paper say to the pencil? Write on.",
    "What did the tired battery say? I'm totally drained.",
    "What did the frog order at the restaurant? French flies and a diet croak.",
    "What did the lettuce say to the celery? Quit stalking me.",
    "What did the ghost say to the bee? Boo bee.",
    "What did the lamp say to the light switch? You turn me on to new ideas.",
    "What did the clock say when it was hungry? I need seconds.",
    "What's orange and sounds like a parrot? A carrot.",
    "What's brown and sticky? A stick.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What's a skeleton's least favorite room? The living room.",
    "What's a vampire's favorite fruit? A neck-tarine.",
    "What's a ghost's favorite dessert? I scream.",
    "What's a pirate's favorite exercise? The plank.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "What's a cat's favorite color? Purrr-ple.",
    "What's a frog's favorite drink? Croak-a-cola.",
    "What's a tree's favorite drink? Root beer.",
    "What's an astronaut's favorite part of a computer? The space bar.",
    "What's a computer's favorite snack? Microchips.",
    "What's a dog's favorite instrument? The trom-bone.",
    "What's a math teacher's favorite season? Sum-mer.",
    "What's a snowman's favorite breakfast? Frosted flakes.",
    "What's a duck's favorite snack? Cheese and quackers.",
    "What's a sheep's favorite dance move? The baaa-llet.",
    "What's a lawyer's favorite drink? Subpoena colada.",
    "What's a bee's favorite haircut? A buzz cut.",
    "What's a scarecrow's favorite fruit? Straw-berries.",
    "What's a mermaid's favorite subject? Algae-bra.",
    "What's a dentist's favorite animal? A molar bear.",
    "What's a librarian's favorite vegetable? Quiet peas.",
    "What's a baker's favorite kind of music? Bread-ock and roll.",
    "What's a turtle's favorite way to travel? Shell-icopter.",
    "What's a ninja's favorite shoe? Sneakers.",
    "What's a whale's favorite game? Swallow the leader.",
    "What's a horse's favorite sport? Stable tennis.",
    "What's a pirate's favorite subject? Arrrt.",
    "What's a banana's favorite gymnastics move? The splits.",
    "What's a cat's favorite dessert? Mice cream.",
    "What's a spider's favorite year? Leap year.",
    "What's a ghost's favorite game? Hide and shriek.",
    "What's a vegetable's favorite martial art? Kale-rate.",
    "What's a computer's favorite beat? An algo-rhythm.",
    "What's a hairdresser's favorite street? The short cut.",
    "What's the most musical part of a turkey? The drumstick.",
    "What's the smartest bee? A spelling bee.",
    "What's the loudest pet? A trum-pet.",
    "I used to be a banker, but I lost interest.",
    "I used to play piano by ear, but now I use my hands.",
    "I used to be addicted to soap, but I'm clean now.",
    "I used to work at a shoe recycling shop. It was sole destroying.",
    "I used to be a tap dancer, until I fell in the sink.",
    "I used to make clocks, but it took too much time.",
    "I used to be a train driver, but I got sidetracked.",
    "I used to be a personal trainer. Then I gave my weight two weeks' notice.",
    "I used to work in a blanket factory, but it folded.",
    "I used to hate math, but then I realized decimals have a point.",
    "I used to run a dating service for chickens, but I struggled to make hens meet.",
    "I used to have a fear of hurdles, but I got over it.",
    "I used to work at a fire hydrant factory. You couldn't park anywhere near the place.",
    "I used to be afraid of speed bumps, but I'm slowly getting over it.",
    "I used to sell ice cream, but I had a meltdown.",
    "I used to be a lumberjack, but I couldn't hack it.",
    "I used to collect candy canes, but they were all in mint condition.",
    "I used to be a gardener, but I didn't have the thyme.",
    "I'm terrified of negative numbers. I'll stop at nothing to avoid them.",
    "I'm so good at sleeping, I can do it with my eyes closed.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "I ate a clock yesterday. It was very time-consuming.",
    "I wondered why the frisbee kept getting bigger. Then it hit me.",
    "I told a chemistry joke once. There was no reaction.",
    "I'm friends with 25 letters of the alphabet. I don't know why.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "I had a dream that I was a muffler. I woke up exhausted.",
    "I accidentally swallowed some food coloring. I feel like I dyed a little inside.",
    "I got hit in the head with a can of soda. Luckily it was a soft drink.",
    "I asked the gym instructor if he could teach me to do the splits. He said, how flexible are you? I said, I can't make Tuesdays.",
    "I'm not a fan of spring cleaning. Let's be honest, I'm not into summer, fall or winter cleaning either.",
    "I gave all my dead batteries away today. Free of charge.",
    "I bought a thesaurus, but all the pages were blank. I have no words to describe how angry I am.",
    "I tried to start a hot air balloon business, but it never took off.",
    "I asked my friend to help me with a hard puzzle. He said, piece of cake. It was a puzzle.",
    "I couldn't figure out how to fasten my seatbelt. Then it clicked.",
    "I went to buy some camouflage pants, but I couldn't find any.",
    "I got a new pair of gloves today, but they're both lefts. On the one hand it's great, but on the other it's just not right.",
    "I've been told I'm condescending. That means I talk down to people.",
    "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
    "I'm starting a new job at a bakery because I knead the dough.",
    "I was going to tell a time-traveling joke, but you guys didn't like it.",
    "I asked a Frenchman if he played video games. He said Wii.",
    "I decided to sell my vacuum. It was just gathering dust.",
    "I can always tell when someone is lying. I can also tell when they're standing.",
    "I bought a wooden whistle, but it wouldn't whistle.",
    "I don't trust trees. They seem kind of shady.",
    "I asked the barista if they had decaf. She said, Sure, we have a few.",
    "I'm thinking about removing my spine. I feel like it's only holding me back.",
    "I told my kids I'd teach them about clocks. It took a lot of time.",
    "I have a fear of moving stairs. I take steps to avoid them.",
    "I wrote a song about a dog. It's a real howler.",
    "I asked my dad if he'd seen the dog bowl. He said he didn't know the dog could play.",
    "Dad, can you put my shoes on? No, they won't fit me.",
    "Dad, I'm hungry. Hi Hungry, I'm Dad.",
    "Dad, did you get a haircut? No, I got them all cut.",
    "Dad, can you make me a sandwich? Poof, you're a sandwich.",
    "Dad, I'm cold. Go stand in the corner, it's 90 degrees there.",
    "Dad, are we pyromaniacs? Yes, we arson.",
    "Dad, what do you think of my new glasses? They're a sight for sore eyes.",
    "Dad, can I watch TV? Sure, just don't turn it on.",
    "Dad, what's your favorite kind of joke? A dad joke, because they're so groan-worthy.",
    "Dad, what time is it? Time to get a watch.",
    "Dad, why is the grass wet? It's dew to the morning.",
    "Where do fish keep their money? In the river bank.",
    "Where do cows go on a Friday night? To the moo-vies.",
    "Where do polar bears vote? The North Poll.",
    "Where do boats go when they're sick? The dock.",
    "Where do pencils go on vacation? Pencil-vania.",
    "Where does a snowman keep his money? In a snow bank.",
    "Where do sheep get their hair cut? At the baa-baa shop.",
    "Where do young trees go to learn? Elemen-tree school.",
    "Where did the computer go dancing? The disc-o.",
    "Where do crayons go on vacation? Color-ado.",
    "Where do burgers go dancing? A meat-ball.",
    "Where do math teachers go on vacation? Times Square.",
    "Where do hamsters go on vacation? Hamster-dam.",
    "Where does a sheep go for vacation? The Baaa-hamas.",
    "Where do rabbits go after their wedding? On a bunny-moon.",
    "Where do ghosts buy their food? At the ghost-ery store.",
    "Where do frogs leave their coats? In the croak room.",
    "Where do cars go swimming? A car pool.",
    "Where do baby cats learn to swim? The kitty pool.",
    "Which bird is always out of breath? A puffin.",
    "Which side of a duck has the most feathers? The outside.",
    "Which day do fish hate? Fry-day.",
    "Which vegetable do sailors hate? Leeks.",
    "Which bow can't be tied? A rainbow.",
    "Which room has no doors or windows? A mushroom.",
    "Which musical instrument is in your ear? The ear drum.",
    "Which state is the loudest? Illi-noise.",
    "Which candy is never on time? Choco-late.",
    "When does a joke become a dad joke? When it becomes apparent.",
    "When is a door not a door? When it's ajar.",
    "When do astronauts eat? At launch time.",
    "When is the best time to buy a bird? When it's going cheep.",
    "When does a cucumber become a pickle? When it's been through a dill-emma.",
    "When do ducks wake up? At the quack of dawn.",
    "When is a car not a car? When it turns into a driveway.",
    "When does it rain money? When there's change in the weather.",
    "When is the moon the heaviest? When it's full.",
    "When does a teacher wear sunglasses? When the students are bright.",
    "Want to hear a joke about a pencil? Never mind, it's pointless.",
    "Want to hear a roof joke? The first one's on the house.",
    "Want to hear a joke about a rope? Skip it.",
    "Want to hear a joke about a shovel? It's groundbreaking.",
    "Want to hear a joke about a train? It'll get you on track.",
    "Want to hear a joke about a cheese? It's very gouda.",
    "Want to hear a joke about a bed? It hasn't been made up yet.",
    "Did you hear about the claustrophobic astronaut? He just needed a little space.",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "Did you hear about the guy who invented the knock-knock joke? He won the No-bell prize.",
    "Did you hear about the actor who fell through the floor? He was just going through a stage.",
    "Did you hear about the new restaurant called Karma? There's no menu, you get what you deserve.",
    "Did you hear about the circus fire? It was in tents.",
    "Did you hear about the two thieves who stole a calendar? They each got six months.",
    "Did you hear about the man who lost the left side of his body? He's all right now.",
    "Did you hear about the cow who tried to jump over a barbed wire fence? It was udder destruction.",
    "Did you hear about the scientist who made a clone of himself? He was beside himself.",
    "Did you hear about the guy who got hit by a rental car? It was Hertz.",
    "Did you hear about the bed bugs who fell in love? They're getting married in the spring.",
    "Did you hear about the cat that swallowed a ball of wool? She had mittens.",
    "Did you hear about the restaurant that only serves burgers to cats? Business is purring.",
    "Did you hear about the shy pebble? It wanted to be a little boulder.",
    "Did you hear about the fire at the shoe factory? Many soles were lost.",
    "Did you hear about the new broom? It's sweeping the nation.",
    "Did you hear the rumor about butter? Never mind, I shouldn't spread it.",
    "Did you hear about the hat that went to college? It graduated at the top of its class.",
    "Did you hear about the boxer who fell asleep? He was knocked out.",
    "Knock knock. Who's there? Lettuce. Lettuce who? Lettuce in, it's cold out here.",
    "Knock knock. Who's there? Boo. Boo who? Don't cry, it's just a joke.",
    "Knock knock. Who's there? Interrupting cow. Interrupting cow w- MOO.",
    "Knock knock. Who's there? Tank. Tank who? You're welcome.",
    "Knock knock. Who's there? Cows go. Cows go who? No, cows go moo.",
    "Knock knock. Who's there? Olive. Olive who? Olive you and I miss you.",
    "Knock knock. Who's there? Nobel. Nobel who? No bell, that's why I knocked.",
    "Knock knock. Who's there? Wooden shoe. Wooden shoe who? Wooden shoe like to hear another joke?",
    "Knock knock. Who's there? Atch. Atch who? Bless you.",
    "Knock knock. Who's there? Dishes. Dishes who? Dishes a very bad joke.",
    "Knock knock. Who's there? Ice cream. Ice cream who? Ice cream every time I see a ghost.",
    "Knock knock. Who's there? Harry. Harry who? Harry up and open the door.",
    "Knock knock. Who's there? Orange. Orange who? Orange you glad I didn't say banana?",
    "Knock knock. Who's there? Justin. Justin who? Justin time for dinner.",
    "Knock knock. Who's there? Alpaca. Alpaca who? Alpaca the snacks, you pack the drinks.",
    "My streaming chair squeaks every time I lean back. It's always got something to say about my gameplay.",
    "My webcam asked for a raise. It said it's been watching me work for years.",
    "The microphone went to therapy. It had too much feedback.",
    "My headset broke up with me. It said I never listen.",
    "I tried to stream from a farm. The bandwidth was full of hay.",
    "My chat asked for a dad joke. So I told them about my lag. It took forever to land.",
    "The keyboard went to the doctor. It had a bad case of caps lock.",
    "My mouse ran away from home. It was tired of being clicked on.",
    "The pixel went to art school. It wanted to be part of a bigger picture.",
    "The emote went to the gym. It wanted to get more reps in chat.",
    "My internet went out for five minutes. I had to talk to my family. They seem nice.",
    "The loading screen went on vacation. It said it'll be back in a moment.",
    "I told my router a joke. It didn't get the connection.",
    "The video game hero got a job as a baker. He was great at leveling up the dough.",
    "My camera told me to smile. I said I'm focusing.",
    "The chat bot went on a diet. It cut back on its bytes.",
    "My laptop started sneezing. I think it caught a bug.",
    "My USB cable was nervous. It took three tries to get in.",
    "The hard drive went to a party. It had a great memory of the night.",
    "The spreadsheet went to school. It wanted to excel.",
    "My printer is very musical. It's always jamming.",
    "The scanner got a job as a detective. It's great at picking up details."
];

// Indexes of the last few jokes told, as a JSON array, newest last. Losing a
// write to a race only means a joke might repeat sooner, so a plain set is
// enough here; no compareAndSet loop.
var RECENT_KEY = "recent";
var RECENT_LIMIT = 100;

/** @param {import("@woofx3/module-sdk/function-ctx").Ctx} ctx */
function dadjoke(ctx) {
    var recent = readRecent(ctx);
    var index = pickIndex(recent);

    recent.push(index);
    if (recent.length > RECENT_LIMIT) {
        recent = recent.slice(recent.length - RECENT_LIMIT);
    }
    try {
        ctx.storage.set(RECENT_KEY, JSON.stringify(recent));
    } catch (e) {
        // Storage is only a nicety here; the joke still goes out.
    }

    var joke = JOKES[index];
    var result = reply(ctx, true, joke);
    result.joke = joke;
    return result;
}

function pickIndex(recent) {
    var skip = {};
    for (var i = 0; i < recent.length; i++) {
        skip[recent[i]] = true;
    }
    var fresh = [];
    for (var j = 0; j < JOKES.length; j++) {
        if (!skip[j]) {
            fresh.push(j);
        }
    }
    var pool = fresh.length > 0 ? fresh : JOKES.map(function (_, k) { return k; });
    return pool[Math.floor(Math.random() * pool.length)];
}

function readRecent(ctx) {
    var raw;
    try {
        raw = ctx.storage && ctx.storage.get(RECENT_KEY);
    } catch (e) {
        return [];
    }
    if (typeof raw !== "string" || raw === "") {
        return [];
    }
    try {
        var parsed = JSON.parse(raw);
        return Array.isArray(parsed)
            ? parsed.filter(function (n) { return typeof n === "number" && n >= 0 && n < JOKES.length; })
            : [];
    } catch (e) {
        return [];
    }
}

// A command's actions reach chat only through the chat extension: the
// command path does not turn a returned ctx.response into a reply. The same
// text rides on the result for a workflow to reuse as ${step.message}.
function reply(ctx, ok, message) {
    if (ctx.chat && typeof ctx.chat.sendMessage === "function") {
        ctx.chat.sendMessage(message);
    }
    var result = ctx.response(ok, message);
    result.ok = ok;
    return result;
}
